<?php

namespace App\Models;

use App\Enums\GuardEnum;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Spatie\Permission\Models\Role as SpatieRole;

class Roles extends SpatieRole
{
    protected $fillable = [
        'name', 'guard_name', 'description'
    ];

    protected $guard_name = GuardEnum::GUARD_NAME;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function groups()
    {
        return $this->belongsToMany(Groups::class,'group_role','role_id','group_id');
    }

    public function permissions(): BelongsToMany
    {
        return parent::permissions(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $query
     * @param $sort
     * @return mixed
     */
    public function scopeGroupsSort($query, $sort)
    {
        return $query->with('groups')->orderBy('id',$sort);
    }

    /**
     * @return int
     */
    public function getGroupsCountAttribute()
    {
        return $this->groups()->count();
    }

    public function getPermissionsTreeAttribute()
    {
        return Permissions::getTreePermissions();
    }

    public function getGroupsIdByRole()
    {
        $ids = [];
        foreach ($this->groups as $group)
        {
            $ids[] = $group->id;
        }
        return $ids;
    }

}
