<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(CountryTableSeeder::class);
        $this->call(LanguagesTableSeeder::class);
        $this->call(CurrencyTableSeeder::class);
        $this->call(ModulesTableSeeder::class);
        $this->call(CompanyTableSeeder::class);
        $this->call(ProjectTableSeeder::class);
        $this->call(GroupTableSeeder::class);
        $this->call(TwoFactorAuthTableSeeder::class);
        $this->call(PaymentProviderTableSeeder::class);
        $this->call(PaymentSystemTableSeeder::class);
        $this->call(ApplicantRiskLevelTableSeeder::class);
        $this->call(ApplicantKycLevelTableSeeder::class);
        $this->call(ApplicantStateReasonTableSeeder::class);
        $this->call(ApplicantStateTableSeeder::class);
        $this->call(ApplicantStatusTableSeeder::class);
        $this->call(ApplicantLabelsTableSeeder::class);
        $this->call(ApplicantCompanyLabelsTableSeeder::class);
        $this->call(PaymentStatusSeed::class);
        $this->call(FeeTypeSeeder::class);
        $this->call(FeePeriodSeeder::class);
        $this->call(TransferTypeTableSeeder::class);
        $this->call(OperationTypeSeeder::class);
        $this->call(AccountStatesTableSeeder::class);
        $this->call(DepartmentSeeder::class);
        $this->call(DepartmentPositionTableSeeder::class);
        $this->call(DepartmentPositionRelationSeeder::class);
        $this->call(MembersTableSeeder::class);
        $this->call(CommissionTemplateLimitTypeTableSeeder::class);
        $this->call(CommissionTemplateTableSeeder::class);
        $this->call(RolesTableSeeder::class);
        $this->call(PermissionsSeeder::class);
        $this->call(SuperAdminSeeder::class);
        $this->call(GroupRoleTableSeeder::class);
        $this->call(GroupRoleMembersIndividualsTableSeeder::class);
        $this->call(ApplicantIndividualTableSeeder::class);
        $this->call(EmailSmtpsTableSeeder::class);
        $this->call(EmailTemplatesTableSeeder::class);
        $this->call(ApplicantIndividualCompanyPositionTableSeeder::class);
        $this->call(ApplicantIndividualCompanyRelationTableSeeder::class);
        $this->call(ApplicantCompaniesTableSeeder::class);
        $this->call(ApplicantIndividualCompanyTableSeeder::class);
        $this->call(ApplicantCompanyModulesTableSeeder::class);
        $this->call(EmailNotificationsTableSeeder::class);
        $this->call(EmailNotificationTemplatesTableSeeder::class);
        $this->call(RegionsTableSeeder::class);
        $this->call(RegionCountriesTableSeeder::class);
        $this->call(ActiveSessionTableSeeder::class);
        $this->call(ActiveSessionTestDbTableSeeder::class);
        $this->call(AuthenticationLogTableSeeder::class);
        $this->call(ActivityLogTableSeeder::class);
        $this->call(ActivityLogTestDbTableSeeder::class);
        $this->call(FeeModesSeeder::class);
        $this->call(QuoteProviderTableSeeder::class);
        $this->call(CommissionPriceListTableSeeder::class);
        $this->call(PriceListFeesTableSeeder::class);
        $this->call(PriceListFeeCurrencyTableSeeder::class);
        $this->call(BankCorrespondentTableSeeder::class);
        $this->call(BankCorrespondentCurrenciesRegionsSeeder::class);
        $this->call(PaymentBankTableSeeder::class);
        $this->call(PaymentBankCurrenciesRegionsSeeder::class);
        $this->call(FileTableSeeder::class);
        $this->call(PaymentProviderIbanTableSeeder::class);
        $this->call(AccountTableSeeder::class);
        $this->call(ApplicantBankingAccessTableSeeder::class);
        $this->call(PaymentUrgencyTableSeeder::class);
        $this->call(RespondentFeesTableSeeder::class);
        $this->call(CommissionTemplateBusinessActivityTableSeeder::class);
        $this->call(RoleActionsSeeder::class);
        $this->call(OuthClientsTableSeeder::class);
        $this->call(PaymentsTableSeeder::class);
        $this->call(DocumentStateTableSeeder::class);
        $this->call(DocumentTypeTableSeeder::class);
        $this->call(ApplicantDocumentTableSeeder::class);
        $this->call(GroupRoleProvidersTableSeeder::class);
        $this->call(PaymentSystemRegionsTableSeeder::class);
        $this->call(TicketStatusTableSeeder::class);
        $this->call(TicketTableSeeder::class);
        $this->call(AccountLimitsTableSeeder::class);
        $this->call(CommissionTemplateLimitTableSeeder::class);
        $this->call(ApplicantIndividualNotesTableSeeder::class);
        $this->call(MemberAccessLimitationsTableSeeder::class);
        $this->call(MemberAccessLimitationsGroupRolesTableSeeder::class);
        $this->call(CompanyModulesTableSeeder::class);
        $this->call(PaymentProviderIbanTableSeeder::class);
        $this->call(TransferIncomingTableSeeder::class);
        $this->call(TransferOutgoingTableSeeder::class);
        $this->call(AccountReachedLimitsTableSeeder::class);
        $this->call(FeeTableSeeder::class);
        $this->call(TransferSwiftsTableSeeder::class);
        $this->call(KycTimelineTableSeeder::class);
        $this->call(CurrencyExchangeRateTableSeeder::class);
        $this->call(ProjectSettingsTableSeeder::class);
        $this->call(AccountClientsTableSeeder::class);
        $this->call(StateTableSeeder::class);
        $this->call(TransferExchangeTableSeeder::class);
        $this->call(TransferFileRelationsTableSeeder::class);
        $this->call(PaymentProviderHistoriesTableSeeder::class);
    }
}
