server:
  address: ":50920"
  public_url: "https://dev.api.docudots.com/"
db:
  connection_string: "postgres://user:password@localhost/dbname?sslmode=disable"
redis:
  connection_string: "localhost:6379"
  pass: ""
  queue_name: "payment-service"
providers:
  clearjunction:
    base_url: "https://sandbox.clearjunction.com/"
    wallet: "11111111-1111-1111-1111-111111111111"
    key: "22222222-2222-2222-2222-222222222222"
    password: "33pr3newpass"
    request_rate: "1s"
    iban_timeout: "60s"
  currencycloud:
    base_url: "https://devapi.currencycloud.com/"
    login_id: "your_login_here"
    api_key: "2222222222222222222222222222222222222222222222222222222222222222"
    rpm_limit:
      convert: 150.0
