server:
  address: ":50920"
db:
  connection_string: "postgres://user:password@localhost/dbname?sslmode=disable"
redis:
  connection_string: "localhost:6379"
  pass: ""
providers:
  clearjunction:
    url: "https://sandbox.clearjunction.com/"
    wallet: "11111111-1111-1111-1111-111111111111"
    key: "22222222-2222-2222-2222-222222222222"
    password: "33pr3newpass"
