version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment-service
    ports:
      - "65432:5432"
    networks:
      backend:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "payment-service"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  ap:
    build:
      context: .
      dockerfile: dockerfiles/ap.Dockerfile
    ports:
      - "50920:50920"
    expose:
      - 50920
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
    networks:
      backend:
    environment:
      DB_CONNECTION_STRING: postgres://postgres:postgres@db:5432/payment-service?sslmode=disable
      RABBITMQ_CONNECTION_STRING: amqp://guest:guest@mq:5672/

  mq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      backend:
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data:

networks:
  backend:
    external: true
