<?php

use App\Models\PermissionOperation;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class InserPermissionsOperationsData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $operations = [
            [8, 'GetIndividualLabel', 'applicants/individual/full-profile/profile/general'],
            [10, 'GetApplicantIndividualManager', 'applicants/individual/full-profile/profile/general'],
            [13, 'GetApplicantIndividualInfo', 'applicants/individual/full-profile/profile/general'],
            [15, 'GetIndividualNote', 'applicants/individual/full-profile/profile/general'],
            [11, 'GetApplicantIndividualProfileData', 'applicants/individual/full-profile/profile/general'],
            [9, 'GetCompanyMembers', 'applicants/individual/full-profile/profile/general'],
            [16, 'GetRiskLevel', 'applicants/individual/full-profile/profile/general'],
            [12, 'GetApplicantIndividualAddress', 'applicants/individual/full-profile/profile/general'],
            [17, 'GetIndividualRiskLevel', 'applicants/individual/full-profile/profile/general'],
            [4, 'GetIndividualsList', 'applicants/individual/list'],
            [3, 'GetApplicantTableSelects', 'applicants/individual/list'],
            [2, 'getAllIndividualCompanies', 'applicants/individual/list'],
            [6, 'GetGroupsListByType', 'applicants/individual/full-profile/profile/general'],
            [14, 'GetApplicantIndividualContacts', 'applicants/individual/full-profile/profile/general'],
            [5, 'GetFilterFieldsData', 'applicants/individual/full-profile/profile/general'],
            [7, 'GetApplicantIndividualsData', 'applicants/individual/full-profile/profile/general'],
            [25, 'CreateIndividualRiskLevel', 'applicants/individual/full-profile/profile/general'],
            [21, 'UpdateApplicantIndividualProfileData', 'applicants/individual/full-profile/profile/general'],
            [22, 'SaveIndividualLabel', 'applicants/individual/full-profile/profile/general'],
            [24, 'UpdateApplicantIndividualAddress', 'applicants/individual/full-profile/profile/general'],
            [23, 'UpdateApplicantIndividualContacts', 'applicants/individual/full-profile/profile/general'],
            [19, 'UpdateApplicantIndividualManager', 'applicants/individual/full-profile/profile/general'],
            [20, 'UpdateApplicantIndividualInfo', 'applicants/individual/full-profile/profile/general'],
            [26, 'CreateIndividualNote', 'applicants/individual/full-profile/profile/general'],
            [27, 'GetApplicantCompaniesData', 'applicants/individual/full-profile/profile/general'],
            [28, 'CreateIndividual', 'applicants/new/individual/profile/general'],
            [47, 'GetApplicantCompanyPageData', 'applicants/company/full-profile/profile/general'],
            [48, 'GetCompanyMembers', 'applicants/company/full-profile/profile/general'],
            [29, 'GetApplicantIndividualsData', 'applicants/individual/full-profile/profile/settings'],
            [30, 'GetIndividual', 'applicants/individual/full-profile/profile/settings'],
            [31, 'GetIndividualModules', 'applicants/individual/full-profile/profile/settings'],
            [32, 'GetApplicantIndividualPhone', 'applicants/individual/full-profile/profile/settings'],
            [33, 'GetApplicantCompanyBankingAccess', 'applicants/individual/full-profile/profile/settings'],
            [34, 'GetGroupsListByType', 'applicants/individual/full-profile/profile/settings'],
            [49, 'GetApplicantCompanyManager', 'applicants/company/full-profile/profile/general'],
            [50, 'GetApplicantCompanyLabel', 'applicants/company/full-profile/profile/general'],
            [51, 'GetApplicantCompanyProfileData', 'applicants/company/full-profile/profile/general'],
            [52, 'GetApplicantCompanyAddress', 'applicants/company/full-profile/profile/general'],
            [53, 'GetApplicantCompanyInfo', 'applicants/company/full-profile/profile/general'],
            [54, 'GetApplicantCompanyContacts', 'applicants/company/full-profile/profile/general'],
            [55, 'GetApplicantCompanyNote', 'applicants/company/full-profile/profile/general'],
            [56, 'GetApplicantMatchedUsers', 'applicants/company/full-profile/profile/general'],
            [57, 'GetRiskLevel', 'applicants/company/full-profile/profile/general'],
            [58, 'GetIndividualRiskLevel', 'applicants/company/full-profile/profile/general'],
            [35, 'updateApplicantIndividual', 'applicants/individual/full-profile/profile/settings'],
            [36, 'UpdateApplicantIndividualPhone', 'applicants/individual/full-profile/profile/settings'],
            [37, 'UpdateApplicantIndividualPassword', 'applicants/individual/full-profile/profile/settings'],
            [38, 'CreateIndividualModules', 'applicants/individual/full-profile/profile/settings'],
            [39, 'UpdateApplicantIndividualModule', 'applicants/individual/full-profile/profile/settings'],
            [40, 'GetApplicantCompanyTableSelects', 'applicants/company/list'],
            [41, 'getAllIndividualCompanies', 'applicants/company/list'],
            [42, 'GetApplicantCompanyList', 'applicants/company/list'],
            [43, 'CreateIndividual', 'applicants/new/company/profile/general'],
            [45, 'GetCompanyMembers', 'applicants/new/company/profile/general'],
            [46, 'GetCompany', 'applicants/new/company/profile/general'],
            [59, 'GetApplicantCompaniesData', 'applicants/company/full-profile/profile/general'],
            [61, 'SaveApplicantCompanyLabel', 'applicants/company/full-profile/profile/general'],
            [67, 'CreateApplicantMatchedUsers', 'applicants/company/full-profile/profile/general'],
            [65, 'UpdateApplicantCompanyAddress', 'applicants/company/full-profile/profile/general'],
            [68, 'UpdateApplicantMatchedUsers', 'applicants/company/full-profile/profile/general'],
            [60, 'UpdateApplicantCompanyManager', 'applicants/company/full-profile/profile/general'],
            [66, 'CreateApplicantCompanyNote', 'applicants/company/full-profile/profile/general'],
            [63, 'UpdateApplicantCompanyProfileData', 'applicants/company/full-profile/profile/general'],
            [62, 'UpdateApplicantCompanyInfo', 'applicants/company/full-profile/profile/general'],
            [64, 'UpdateApplicantCompanyContacts', 'applicants/company/full-profile/profile/general'],
            [69, 'CreateIndividualRiskLevel', 'applicants/company/full-profile/profile/general'],
            [70, 'GetApplicantCompanyPageData', 'applicants/company/full-profile/profile/settings'],
            [71, 'GetApplicantCompanyModules', 'applicants/company/full-profile/profile/settings'],
            [72, 'GetApplicantCompanyPhone', 'applicants/company/full-profile/profile/settings'],
            [73, 'GetApplicantCompanyBankingAccess', 'applicants/company/full-profile/profile/settings'],
            [1, 'getMemberData', NULL],
            [74, 'GetGroupsListByType', 'applicants/company/full-profile/profile/settings'],
            [75, 'GetAllCountries', 'applicants/company/full-profile/profile/settings'],
            [76, 'UpdateApplicantCompanyPhone', 'applicants/company/full-profile/profile/settings'],
            [77, 'UpdateApplicantCompany', 'applicants/company/full-profile/profile/settings'],
            [78, 'CreateApplicantCompanyModule', 'applicants/company/full-profile/profile/settings'],
            [79, 'UpdateApplicantCompanyModule', 'applicants/company/full-profile/profile/settings'],
            [81, 'GET_ALL_COMPANIES', 'settings/manager-roles/list'],
            [82, 'GetManagerRoleList', 'settings/manager-roles/list'],
            [83, 'GetRolesName', 'settings/manager-roles/list'],
            [84, 'GetGroupsName', 'settings/manager-roles/new'],
            [85, 'GetRolesByFilter', 'settings/manager-roles/new'],
            [86, 'GetAllPermissions', 'settings/manager-roles/new'],
            [87, 'CreateManagerRole', 'settings/manager-roles/new'],
            [88, 'GetManagerRole', 'settings/manager-roles/edit'],
            [89, 'GetRolesByFilter', 'settings/manager-roles/edit'],
            [90, 'UpdateManagerRole', 'settings/manager-roles/edit'],
            [91, 'GroupsByFilter', 'settings/manager-groups/list'],
            [92, 'GetRolesName', 'settings/manager-groups/list'],
            [93, 'GetGroups', 'settings/manager-groups/list'],
            [94, 'GetGroupsTableSelects', 'settings/manager-groups/list'],
            [96, 'GetGroupsTableSelects', 'settings/manager-groups/new-group'],
            [97, 'GetRolesByCompany', 'settings/manager-groups/new-group'],
            [98, 'CheckGroups', 'settings/manager-groups/new-group'],
            [99, 'CreateGroupSetting', 'settings/manager-groups/new-group'],
            [100, 'DeleteGroupSetting', 'settings/manager-groups/list'],
            [101, 'GetPaymentsList', 'settings/payment-list'],
            [104, 'UpdatePayment', 'settings/payment-list'],
            [102, 'CreatePayment', 'settings/payment-list'],
            [103, 'DeletePayment', 'settings/payment-list'],
            [105, 'GetAdministrationCompanyList', 'administration/company/list'],
            [107, 'GetFilterFieldsData', 'administration/company/list'],
            [108, 'CreateMemberCompanyQuery', 'administration/company/list'],
            [109, 'DeleteMemberCompanyQuery', 'administration/company/list'],
            [112, 'GetMemberByField', NULL],
            [113, 'getMemberCompanies', 'administration/members/list'],
            [114, 'GetMembersList', 'administration/members/list'],
            [115, 'GetFilterFieldsTableData', 'administration/members/list']
        ];
        $binds =collect([
            [1, 2],
            [1, 3],
            [1, 4],
            [2, 2],
            [2, 3],
            [2, 4],
            [11, 19],
            [11, 10],
            [12, 19],
            [12, 10],
            [13, 22],
            [13, 8],
            [14, 26],
            [14, 15],
            [15, 9],
            [15, 6],
            [15, 27],
            [16, 16],
            [16, 17],
            [16, 25],
            [4, 28],
            [9, 5],
            [10, 5],
            [9, 7],
            [10, 7],
            [9, 11],
            [10, 11],
            [9, 12],
            [10, 12],
            [9, 13],
            [10, 13],
            [9, 14],
            [10, 14],
            [10, 20],
            [10, 21],
            [10, 23],
            [10, 24],
            [20, 36],
            [21, 38],
            [21, 31],
            [21, 39],
            [22, 33],
            [17, 29],
            [17, 30],
            [18, 29],
            [18, 30],
            [20, 32],
            [17, 34],
            [18, 34],
            [18, 35],
            [18, 37],
            [5, 40],
            [5, 41],
            [5, 42],
            [8, 43],
            [8, 45],
            [8, 46],
            [25, 47],
            [26, 47],
            [31, 48],
            [27, 49],
            [28, 49],
            [29, 50],
            [25, 51],
            [26, 51],
            [25, 52],
            [26, 52],
            [25, 53],
            [26, 53],
            [25, 54],
            [26, 54],
            [30, 55],
            [25, 56],
            [26, 56],
            [32, 57],
            [32, 58],
            [31, 59],
            [27, 60],
            [28, 60],
            [29, 61],
            [26, 62],
            [26, 63],
            [26, 64],
            [26, 65],
            [30, 66],
            [26, 67],
            [26, 68],
            [32, 69],
            [33, 70],
            [34, 70],
            [37, 71],
            [36, 72],
            [35, 73],
            [33, 74],
            [34, 74],
            [33, 75],
            [34, 75],
            [36, 76],
            [34, 77],
            [37, 78],
            [37, 79],
            [41, 81],
            [42, 81],
            [41, 82],
            [42, 82],
            [41, 83],
            [42, 83],
            [44, 84],
            [44, 85],
            [44, 86],
            [44, 87],
            [45, 88],
            [46, 88],
            [45, 89],
            [46, 89],
            [46, 90],
            [47, 91],
            [47, 92],
            [47, 93],
            [47, 94],
            [48, 91],
            [48, 92],
            [48, 93],
            [48, 94],
            [50, 96],
            [50, 97],
            [50, 98],
            [50, 99],
            [49, 100],
            [53, 101],
            [54, 101],
            [56, 102],
            [55, 103],
            [54, 104],
            [71, 105],
            [71, 107],
            [72, 105],
            [72, 107],
            [74, 108],
            [73, 109],
            [82, 113],
            [82, 114],
            [82, 115],
            [81, 114],
            [81, 113],
            [81, 115],
        ]);
        $parents = collect([
            [1, 28],
            [2, 28],
            [9, 10],
            [10, 10],
            [10, 19],
            [9, 8],
            [10, 8],
            [10, 22],
            [9, 15],
            [10, 15],
            [10, 26],
            [9, 9],
            [9, 6],
            [9, 27],
            [10, 9],
            [10, 6],
            [10, 27],
            [9, 16],
            [10, 16],
            [9, 17],
            [10, 17],
            [10, 25],
            [18, 36],
            [17, 31],
            [18, 31],
            [18, 38],
            [18, 39],
            [17, 33],
            [18, 33],
            [17, 32],
            [18, 32],
            [5, 43],
            [5, 45],
            [5, 46],
            [25, 48],
            [26, 48],
            [25, 49],
            [26, 49],
            [25, 50],
            [26, 50],
            [25, 55],
            [26, 55],
            [25, 57],
            [26, 57],
            [25, 58],
            [26, 58],
            [25, 59],
            [26, 59],
            [26, 60],
            [26, 61],
            [26, 66],
            [26, 69],
            [33, 71],
            [34, 71],
            [33, 72],
            [34, 72],
            [33, 73],
            [34, 73],
            [34, 76],
            [34, 78],
            [34, 79],
            [41, 84],
            [41, 85],
            [41, 86],
            [41, 87],
            [42, 84],
            [42, 85],
            [42, 86],
            [42, 87],
            [47, 96],
            [47, 97],
            [47, 98],
            [47, 99],
            [48, 96],
            [48, 97],
            [48, 98],
            [48, 99],
            [47, 100],
            [48, 100],
            [53, 102],
            [54, 102],
            [53, 103],
            [54, 103],
            [71, 108],
            [72, 109],
            [71, 108],
            [72, 109],

        ]);

        $binds = $binds->groupBy(function ($b){return $b[1];})->map(function ($b){
            return $b->map(function ($s){
                unset($s[1]);
                return $s;
            })->flatten(1);
        });
        $parents = $parents->groupBy(function ($b){return $b[1];})->map(function ($b){
            return $b->map(function ($s){
                unset($s[1]);
                return $s;
            })->flatten(1);
        });


        foreach ($operations as $operation) {
            $newOperation = PermissionOperation::create(array_combine(['id', 'name', 'referer'], $operation));

            if ($binds->has($newOperation->id)) {
                $newOperation->binds()->attach($binds->get($newOperation->id));
            }
            if ($parents->has($newOperation->id)) {
                $newOperation->parents()->attach($parents->get($newOperation->id));
            }
        }


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
